name: WoBBoB WiZArD: Upload Source

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Add all source files
        run: |
          git config user.name "wobbob89-bot"
          git config user.email "wobbob89-bot@example.com"
          git add .
          git commit -m "Automated: Add/update WoBBoB WiZArD codebase" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
